runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: compile/index.html
  upload: compile/index.html
- url: /experience
  static_files: compile/index.html
  upload: compile/index.html
- url: /skill
  static_files: compile/index.html
  upload: compile/index.html
- url: /education
  static_files: compile/index.html
  upload: compile/index.html
- url: /interest
  static_files: compile/index.html
  upload: compile/index.html

- url: /(.*)
  static_files: compile/\1
  upload: compile/(.*)

# Recommended file skipping declaration from the GAE tutorials
skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?\..*
  - ^(.*/)?gulp$
  - ^(.*/)?src$
  - ^(.*/)?build$
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - ^gulp\.js
  - ^node_modules/(.*/)?
